sudo: required 
services:
  - docker 
before_install:
  - docker build -t  56778/react-test -f ./client/Dockerfile.dev ././client/Dockerfile.dev
script:
  - docker run 56778/react-test npm test -- ----coverage
after_success:
  - docker build -t  56778/multi-client ./client
  - docker build -t  56778/multi-nginx ./nginx 
  - docker build -t  56778/multi-server ./server 
  - docker build -t  56778/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$$DOCKER_ID" --password-stdin
  - docker push 56778/multi-client
  - docker push 56778/multi-worker
  - docker push 56778/multi-server


